// Package bbk handles scraping timing links that are generated by the
// bbk timing software.
package bbk

import (
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"

	"github.com/FaintLocket424/opengrid-bridge/internal/models"
)

// Scraper represents a scraper that operates on bbk pages.
// Holds a reference to its target URL and HTTP Client to use.
type Scraper struct {
	target string
	client *http.Client
}

// NewScraper creates a new Scraper for bbk for the targetURL using client.
func NewScraper(targetURL string, client *http.Client) *Scraper {
	return &Scraper{
		target: targetURL,
		client: client,
	}
}

// fetchPage makes an HTTP request to the input parameter url using the
// scraper's HTTPClient. It checks if the status is 200 OK and returns
// the Body of the request.
func (s *Scraper) fetchPage(url string) (io.ReadCloser, error) {
	res, err := s.client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("network error: %w", err)
	}

	if res.StatusCode != http.StatusOK {
		if err := res.Body.Close(); err != nil {
			slog.Error("Failed to close response body", "err", err, "url", url)
		}
		return nil, fmt.Errorf("server returned status: %d", res.StatusCode)
	}

	return res.Body, nil
}

// GetLiveTiming calls the scraper to fetch the `liveraceres.htm` page from the
// target and run the parser on it to create a *models.RaceResultsScrape of the
// current live race.
func (s *Scraper) GetLiveTiming() (res *models.RaceResultScrape, err error) {
	body, fetchErr := s.fetchPage(s.target + "/liveraceres.htm")
	if fetchErr != nil {
		return nil, fetchErr
	}
	defer func() {
		if closeErr := body.Close(); closeErr != nil {
			err = errors.Join(err, closeErr)
		}
	}()

	return parseRaceResultHTML(body)
}

// GetPracticeRaceResult calls the scraper to fetch the `pxryres.htm` for a given
// practice heat x and round y.
func (s *Scraper) GetPracticeRaceResult(hr models.HeatRound) (res *models.RaceResultScrape, err error) {
	practiceHeat := hr.Heat
	round := hr.Round

	if practiceHeat < 1 || round < 1 {
		return nil, fmt.Errorf("practice and round must be >= 1 (got %d, %d)", practiceHeat, round)
	}

	url := fmt.Sprintf("%s/p%dr%dres.htm", s.target, practiceHeat, round)
	body, fetchErr := s.fetchPage(url)
	if fetchErr != nil {
		return nil, fetchErr
	}
	defer func() {
		if closeErr := body.Close(); closeErr != nil {
			err = errors.Join(err, closeErr)
		}
	}()

	return parseRaceResultHTML(body)
}

// GetQualiRaceResult calls the scraper to fetch the `hxryres.htm` for a given
// qualifying heat x and round y.
func (s *Scraper) GetQualiRaceResult(hr models.HeatRound) (res *models.RaceResultScrape, err error) {
	qualiHeat := hr.Heat
	round := hr.Round

	if qualiHeat < 1 || round < 1 {
		return nil, fmt.Errorf("heat and round must be >= 1 (got %d, %d)", qualiHeat, round)
	}

	url := fmt.Sprintf("%s/h%dr%dres.htm", s.target, qualiHeat, round)
	body, fetchErr := s.fetchPage(url)
	if fetchErr != nil {
		return nil, fetchErr
	}
	defer func() {
		if closeErr := body.Close(); closeErr != nil {
			err = errors.Join(err, closeErr)
		}
	}()

	return parseRaceResultHTML(body)
}

// GetFinalRaceResult calls the scraper to fetch the `fxryres.htm` for a given
// final number x and round y.
func (s *Scraper) GetFinalRaceResult(hr models.HeatRound) (res *models.RaceResultScrape, err error) {
	finalNumber := hr.Heat
	leg := hr.Round

	if finalNumber < 1 || leg < 1 {
		return nil, fmt.Errorf("final and leg must be >= 1 (got %d, %d)", finalNumber, leg)
	}

	url := fmt.Sprintf("%s/f%dr%dres.htm", s.target, finalNumber, leg)
	body, fetchErr := s.fetchPage(url)
	if fetchErr != nil {
		return nil, fetchErr
	}
	defer func() {
		if closeErr := body.Close(); closeErr != nil {
			err = errors.Join(err, closeErr)
		}
	}()

	return parseRaceResultHTML(body)
}

// GetRaceResultsIndex calls the scraper to get the `liveresults.htm` index page and parse it
// for all the links.
func (s *Scraper) GetRaceResultsIndex() (res *models.RaceResultsIndexScrape, err error) {
	body, fetchErr := s.fetchPage(s.target + "/liveresults.htm")
	if fetchErr != nil {
		return nil, fetchErr
	}
	defer func() {
		if closeErr := body.Close(); closeErr != nil {
			err = errors.Join(err, closeErr)
		}
	}()

	return parseRaceResultsIndexHTML(body)
}

// GetRaceSchedule calls the scraper to fetch the `liveschedule.htm` page from the
// target and run the parser on it to create a *models.RaceScheduleScrape of the
// current race schedule.
func (s *Scraper) GetRaceSchedule() (res *models.RaceScheduleScrape, err error) {
	body, fetchErr := s.fetchPage(s.target + "/liveschedule.htm")
	if fetchErr != nil {
		return nil, fetchErr
	}
	defer func() {
		if closeErr := body.Close(); closeErr != nil {
			err = errors.Join(err, closeErr)
		}
	}()

	return parseRaceScheduleHTML(body)
}
