name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Formatting, Linters, and Unit Tests
        # Runs the checks: `go-test`, `golangci-lint`, and `formatting`
        run: nix flake check -L

      - name: Build Packages
        run: nix build .#default -L
